/**
 * @author Jack Polk
 * @version 4/16/18
 * @purpose: This class calculates the ammount of CO2 produced by a certain ammount
 *           of gallons of gas.
 * It contains mutator methods to calculate the ammount of CO2 generated and to
 * convert from tons to pounds
 * It contains getter methods to fetch the number of gallons, tons of CO2, and
 * pounds of CO2
 * Private instance variables include the number of gallons used, the ammount of
 * CO2 in tons and the ammount of CO2 in pounds
 *
 */
public class CO2FootprintV2
{
    private double myGallonsUsed, myTonsCO2, myPoundsCO2;

    /**
     * Constructor for objects of type CO2FootprintV2
     * @param gallons Ammount of petrol in gallons
     * Precondition: gallons is a positive value
     */
    CO2FootprintV2(double gallons)
    {
        myGallonsUsed = gallons;
    }

    /**
     * Mutator method from CO2FootprintV2
     * Calculates the ammount, in tons, of CO2 produced by a certain ammount of
     * petrol in gallons
     * Precondition: myGallonsUsed exists
     */
    public void calcTonsCO2()
    {
        myTonsCO2 = (8.78 * Math.pow(10, -3)) * myGallonsUsed; //This is a formula used to calculate the ammount of CO2 generated by a certain ammount of petrol
    }

    /**
     * Mutator method from CO2FootprintV2
     * Converts from tons to pounds
     * Precondition: myPoundsCO2 exists
     */
    public void convertTonsToPounds()
    {
        myPoundsCO2 = myTonsCO2 * 2205; //2205 is the conversion factor between pounds and tons (1 ton ≈ 2205lb)
    }

    /**
     * Getter method from CO2FootprintV2
     * Returns the ammount, in gallons, of petrol that has been used
     * Precondition: myGallonsUsed exists
     */
    public double getGallons()
    {
        return myGallonsUsed;
    }

    /**
     * Getter method from CO2FootprintV2
     * Returns the ammount of CO2 created, in tons
     * Precondition: myTonsCO2 exists
     */
    public double getTonsCO2()
    {
        return myTonsCO2;
    }

    /**
     * Getter method from from CO2FootprintV2
     * Returns the ammount of CO2 created, in pounds
     * Precondition: getPoundsCO2 exists
     */
    public double getPoundsCO2()
    {
        return myPoundsCO2;
    }
}
